apiVersion: v1
kind: Service
metadata:
  name: sistema-lanchonete-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: sistema-lanchonete
